Repository geosolutions-it/austrocontrol-C125, pull requests merged in 2020-12, with the labels that each got.

#251 Plugin import fix
  js/components/timeFilter/DateFilter.jsx
  js/plugins.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, bug

#252 Measure panel translation texts for tooltip
  translations/data.de-DE.json
  translations/data.en-US.json
Labels: C125-2020-AUSTROCONTROL-Map2Imp

#256 #253: Embedded is missing
  embedded.html
  embeddedTemplate.html
  js/apiPlugins.js
  js/appConfigEmbedded.js
  js/embedded.js
  package.json
  prod-webpack.config.js
  webpack.config.js
Labels: C125-2020-AUSTROCONTROL-Map2Imp, Priority: Medium
